#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-python_levenshtein
Version  : 0.12.2
Release  : 41
URL      : https://files.pythonhosted.org/packages/2a/dc/97f2b63ef0fa1fd78dcb7195aca577804f6b2b51e712516cc0e902a9a201/python-Levenshtein-0.12.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/2a/dc/97f2b63ef0fa1fd78dcb7195aca577804f6b2b51e712516cc0e902a9a201/python-Levenshtein-0.12.2.tar.gz
Summary  : Python extension for computing string edit distances and similarities.
Group    : Development/Tools
License  : GPL-2.0
Requires: pypi-python_levenshtein-license = %{version}-%{release}
Requires: pypi-python_levenshtein-python = %{version}-%{release}
Requires: pypi-python_levenshtein-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: python-Levenshtein
Provides: python-Levenshtein-python
Provides: python-Levenshtein-python3
BuildRequires : pypi(setuptools)
BuildRequires : python3-dev

%description
Maintainer wanted
        -----------------
        
        |MaintainerWanted|_

%package license
Summary: license components for the pypi-python_levenshtein package.
Group: Default

%description license
license components for the pypi-python_levenshtein package.


%package python
Summary: python components for the pypi-python_levenshtein package.
Group: Default
Requires: pypi-python_levenshtein-python3 = %{version}-%{release}

%description python
python components for the pypi-python_levenshtein package.


%package python3
Summary: python3 components for the pypi-python_levenshtein package.
Group: Default
Requires: python3-core
Provides: pypi(python_levenshtein)
Requires: pypi(setuptools)

%description python3
python3 components for the pypi-python_levenshtein package.


%prep
%setup -q -n python-Levenshtein-0.12.2
cd %{_builddir}/python-Levenshtein-0.12.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641483818
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-python_levenshtein
cp %{_builddir}/python-Levenshtein-0.12.2/COPYING %{buildroot}/usr/share/package-licenses/pypi-python_levenshtein/07102fa3ba93fed83e4cab3681f311908c1a7c93
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-python_levenshtein/07102fa3ba93fed83e4cab3681f311908c1a7c93

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
